version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - /packages/coverage-badge-readme
      - /packages/export-code
    schedule:
      interval: weekly
    groups:
      prod-dependencies:
        dependency-type: production
      dev-dependencies:
        dependency-type: development
